flask-server/website/views.py
"""
Blueprinty konkretnych widoków na stronie.
"""
import json
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, current_app as app
from flask_login import login_required, current_user
from .models import Comment, Patient, MedicalData, User
from .forms import PatientForm, MedDataForm, CommentForm, UserForm, SearchField
from . import db
import os
from werkzeug.utils import secure_filename
from sqlalchemy import desc, or_

# Tworzenie blueprintu 'views' do obsługi widoków
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    """
    Widok strony głównej.

    Pobiera wszystkich pacjentów i użytkowników z bazy danych
    i renderuje stronę główną.
    """
    patients = Patient.query.order_by(Patient.id)
    users = User.query.order_by(User.id)
    return render_template("home.html", user=current_user, patients=patients, users=users)

@views.route('/com/delete', methods=['POST'])
@login_required
def delete_com():
    """
    Widok usuwania komentarza.

    Pobiera dane komentarza z żądania, usuwa go z bazy danych,
    jeśli użytkownik jest autorem komentarza.
    """
    comment = json.loads(request.data)
    commentId = comment['commentId']
    comment = Comment.query.get(commentId)
    if comment:
        if comment.user_id == current_user.id:
            db.session.delete(comment)
            db.session.commit()
    return jsonify({})

@views.route('/patients', methods=['GET', 'POST'])
@login_required
def patients():
    """
    Widok zarządzania pacjentami.

    Umożliwia dodawanie nowych pacjentów oraz wyszukiwanie istniejących.
    """
    form = PatientForm()
    search = SearchField()
    if form.validate_on_submit():
        patient = Patient.query.filter_by(pesel=form.pesel.data).first()
        if patient is None:
            patient = Patient(name=form.name.data, pesel=form.pesel.data)
            db.session.add(patient)
            db.session.commit()
            flash('Dodano pacjenta', category='success')
            form.data.clear()
            return redirect(url_for('views.patients'))
        else:
            form.pesel.errors.append("Użytkownik o podanym peselu już istnieje")
            
    patients = Patient.query.order_by(Patient.id)        

    if search.validate_on_submit():     
        if search.searchResult.data:
            patients = Patient.query.filter(
                or_(Patient.pesel.like(search.searchResult.data), Patient.name.like(search.searchResult.data))
            )
    return render_template("patients.html", user=current_user, form=form, patients=patients, search=search)

@views.route('/patients/<int:patientId>', methods=['GET', 'POST'])
@login_required
def patientView(patientId):
    """
    Widok szczegółów pacjenta.

    Wyświetla profil pacjenta, komentarze i dane medyczne.
    """
    users = User.query.order_by(User.id)
    patient = Patient.query.get_or_404(patientId)
    comments = Comment.query.filter_by(patient_id=patientId).order_by(desc(Comment.date))
    medicalRecord = MedicalData.query.filter_by(patient_id=patientId).order_by(desc(MedicalData.date))
    
    medform = MedDataForm()
    comform = CommentForm()
    
    return render_template("patient_profile.html", user=current_user, users=users, medform=medform, patient=patient, comform=comform, comments=comments, medicalRecord=medicalRecord)

@views.route('/patients/delete', methods=['POST'])
@login_required
def delete_patient():
    """
    Widok usuwania pacjenta.

    Usuwa pacjenta oraz powiązane z nim dane medyczne i komentarze.
    """
    patient = json.loads(request.data)
    patientId = patient['patientId']
    patient = Patient.query.get_or_404(patientId)
    if patient:
        for meddata in patient.medicalRecord:
            db.session.delete(meddata)
        for opinion in patient.opinions:
            db.session.delete(opinion)
        db.session.delete(patient)
        db.session.commit()
    return jsonify({})

@views.route('/patients/addToMyPatients', methods=['GET', 'POST'])
@login_required
def addToMyPatients():
    """
    Widok dodawania pacjenta do listy moich pacjentów.

    Dodaje wybranego pacjenta do listy pacjentów zalogowanego użytkownika.
    """
    patient = json.loads(request.data)
    patientId = patient['patientId']
    patient = Patient.query.get_or_404(patientId)
    user = User.query.filter_by(id=current_user.id).first()
    user.patient.append(patient)
    db.session.commit()
    return jsonify({})

@views.route('/patients/deleteFromMyPatients', methods=['GET', 'POST'])
@login_required
def deleteFromMyPatients():
    """
    Widok usuwania pacjenta z listy moich pacjentów.

    Usuwa wybranego pacjenta z listy pacjentów zalogowanego użytkownika.
    """
    patient = json.loads(request.data)
    patientId = patient['patientId']
    patient = Patient.query.get_or_404(patientId)
    user = User.query.filter_by(id=current_user.id).first()
    user.patient.remove(patient)
    db.session.commit()
    return jsonify({})

@views.route('/patients/MedData/add/<int:patientId>', methods=['POST'])
@login_required
def addPatMed(patientId):
    """
    Widok dodawania danych medycznych dla pacjenta.

    Dodaje nowe dane medyczne dla wybranego pacjenta.
    """
    patient = Patient.query.get_or_404(patientId)
    users = User.query.order_by(User.id)
    medform = MedDataForm()
    comform = CommentForm()
    
    if medform.submit.data and medform.validate_on_submit():
        filename = ''
        request.files['file']
        
        if medform.file.data:
            file = request.files['file']
            filename = secure_filename(file.filename)
            medform.file.data.save(os.path.join(app.config['IMAGE_UPLOADS'], filename))
        
        new_meddata = MedicalData(
            diagnosis=medform.text.data, user_id=current_user.id, patient_id=patientId, title=medform.title.data, filename=filename
        )
        db.session.add(new_meddata)
        db.session.commit()
        medform.data.clear()
        flash('Dodano dane', category='success')
        return redirect('/patients/' + str(patientId))
    
    return render_template("patient_profile.html", user=current_user, users=users, medform=medform, patient=patient, comform=comform)

@views.route('/patients/delMed', methods=['POST'])
@login_required
def deleteMedData():
    """
    Widok usuwania danych medycznych.

    Usuwa wybrane dane medyczne z bazy danych oraz powiązany plik.
    """
    medicaldata = json.loads(request.data)
    medicaldataId = medicaldata['medicaldataId']
    medicaldata = MedicalData.query.get_or_404(medicaldataId)
    if medicaldata:
        if current_user.id != medicaldata.user_id:
            return redirect(url_for('views.deleteMedData'))
        if medicaldata.filename:
            os.remove(os.path.join(app.config['IMAGE_UPLOADS'], medicaldata.filename))
        db.session.delete(medicaldata)
        db.session.commit()
    return jsonify({})

@views.route('/patients/addCom/<int:patientId>', methods=['POST'])
@login_required
def addPatCom(patientId):
    """
    Widok dodawania komentarza do pacjenta.

    Dodaje nowy komentarz do wybranego pacjenta.
    """
    patient = Patient.query.get_or_404(patientId)
    users = User.query.order_by(User.id)
    medform = MedDataForm()
    comform = CommentForm()
    
    if comform.validate_on_submit():
        new_comment = Comment(text=comform.text.data, user_id=current_user.id, patient_id=patientId)
        db.session.add(new_comment)
        db.session.commit()
        comform.data.clear()
        flash('Dodano', category='success')
        return redirect('/patients/' + str(patientId))
    
    return render_template("patient_profile.html", user=current_user, users=users, medform=medform, patient=patient, comform=comform)

@views.route('/com/add', methods=['POST'])
@login_required
def addCom():
    """
    Widok dodawania komentarza.

    Dodaje nowy komentarz.
    """
    comform = CommentForm()
    
    if comform.validate_on_submit():
        new_comment = Comment(text=comform.text.data, user_id=current_user.id)
        db.session.add(new_comment)
        db.session.commit()
        return redirect('/')
    
    return redirect('/')

@views.route('patients/MedData/<int:meddataId>')
@login_required
def viewMedData(meddataId):
    """
    Widok wyświetlania danych medycznych.

    Wyświetla szczegóły wybranych danych medycznych.
    """
    meddata = MedicalData.query.get_or_404(meddataId)
    patient = Patient.query.get_or_404(meddata.patient_id)
    users = User.query.order_by(User.id)
    return render_template("meddata.html", user=current_user, users=users, patient=patient, meddata=meddata)

# @views.route('/settings/change', methods=['POST'])
# @login_required
# def changeUserData():
    
#     user = User.query.order_by(current_user)
#     form = UserForm()
    
#     if form.submit.data and form.validate_on_submit():
#             picture = ''
#             request.files['file']
            
#             if form.picture.data:
#                 file = request.files['file']
#                 picture = secure_filename(file.picture)
                
#                 print(os.path.join(app.config['IMAGE_UPLOADS'], picture))
#                 form.file.data.save(os.path.join(app.config['IMAGE_UPLOADS'], picture))
                
#             user
#             print(picture)
#             user.name = form.name.data
#             user.surname = form.surname.data
#             user.specialization = form.specialization.data
#             user.description = form.description.data
#             user.contact = form.contact.data
#             user.email = form.email.data
            
#             db.session.commit()
#             flash('Dodano dane', category='success')
#             return redirect('/settings')

#     return redirect('/settings')

flask-server/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="basevieport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
    />
    <title>{%block title%}Med-Wiz{%endblock%}</title>
  </head>

  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark"
      style="background-color: #495e57"
    >
      <a class="navbar-brand" href="#">SIEMA.Inc</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link active" href="/"
            >Mój Profil <span class="sr-only">(current)</span></a
          >
          
          <a class="nav-item nav-link" href="{{url_for('views.patients')}}">Lista Pacjentów</a>       
          <a class="nav-item nav-link" id="login" href="/settings">Settings</a>
          <a class="nav-item nav-link" id="login" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="login" href="/sign-up"
            >Rejestracja</a
          >
          {% endif %}
        </div>
      </div>
    </nav>

    {%with messages = get_flashed_messages(with_categories=true)%} {%if
    messages%} {% for category, message in messages %} {% if category =='error'
    %}
    <div
      align="center"
      class="alert alert-danger alert-dismissable fade show"
      role="alert"
    >
      {{message}}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% elif category=='success' %}
    <div
      align="center"
      class="alert alert-success alert-dismissable fade show"
      role="alert"
    >
      {{message}}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container-fluid px-5 ">{%block content%} {%endblock%}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='index.js') }}"></script>
  </body>
</html>

flask-server/website/templates/home.html
{% extends "base.html" %} 
{% from "jinja_helpers.html" import render_field, render_button, render_checkbox %}

{% block title %}Med-Wiz{% endblock %}

{% block content %}
<h1 align="center">Profil : {{ current_user.name }}</h1>

<div class="container-fluid">
  <div class="row">
    <!-- Left Column: Available Patients -->
    <div class="col-md-5">
      <h2>Dostępni pacjenci</h2>
      <div class="shadow p-3 mb-5 bg-body rounded" style="max-height: 600px; overflow-y: scroll;">
      <table class="table table-hover table-bordered table-striped">
        {% for patient in user.patient %}
        <tr>
          <td>
            {{ patient.id }}. <a href="patients/{{ patient.id }}">{{ patient.name }}</a> - Pesel: {{ patient.pesel }}
            <br />
            <a class="btn btn-primary mt-3" href="{{ url_for('views.patientView', patientId=patient.id) }}">Profil</a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    </div>

    <!-- Right Column: User Data -->
    <div class="col-md-5">
      <h2 align="center">Twoje dane</h2>
      <br />
      <div class="profile">
        <div class="row">
          <div class="col-md-8">
            <ul class="list-group list-group-flush" id="userProfile">
              <li class="list-group-item">
                <b>Imię:</b> {{ user.name }}
              </li>
              <li class="list-group-item">
                <b>Nazwisko:</b> {{ user.surname }}
              </li>
              <li class="list-group-item">
                <b>Specjalizacja:</b> {{ user.specialization }}
              </li>
              <li class="list-group-item">
                <b>Kontakt:</b> {{ user.phonenumber }}
              </li>
              <li class="list-group-item">
                <b>Opis:</b> {{ user.about}}
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            {% if user.picture %}
              <img src="{{ url_for('static', filename='images/'+ user.picture) }}" width="320" height="320" class="img-fluid" alt="PFP"/>
            {% else %}
              Brak zdjęcia
            {% endif %}
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flask-server/website/templates/jinja_helpers.html
{% macro render_field(field) %}
    <div class="form-group">
        {{ field.label(class="form-control-label font-weight-bold text-muted") }}
        {% if field.errors %}
            {{ field(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in field.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% elif field.data != None %}
            {{ field(class="form-control is-valid") }}
        {% else %}
            {{ field(class="form-control") }}
        {% endif %}


    </div>
{% endmacro %}

{%  macro render_checkbox(checkbox) %}
<div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
    {{checkbox.label(class="form-check-label", for="flexCheckDefault") }}
  </div>
{%  endmacro %}
{%  macro render_filefield(input) %}
  {% if input.errors %}
            {{ input(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in input.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
    {% endif %}
{%  endmacro %}

{%  macro render_button(button) %}
    {{ button(class="btn btn-success") }}
{%  endmacro %}

flask-server/website/templates/login.html
{% extends "base.html" %}{% from "jinja_helpers.html" import render_field %} {%
from "jinja_helpers.html" import render_button %}{% from "jinja_helpers.html"
import render_checkbox %} {%block title%}Med-Wiz login{%endblock%} {%block
content%}
<br />
<div class="shadow p-3 mb-5 bg-body rounded">
  <form method="post" novalidate="true">
    <br />
    {{ form.csrf_token }} {{form.hidden_tag()}} {{render_field(form.email)}}
    <br />
    {{render_field(form.password)}}
    <br />
    {{render_checkbox(form.remember)}}
    <br />
    {{render_button(form.submit)}}
  </form>
</div>
{%endblock%}

flask-server/website/templates/meddata.html
{% extends "base.html" %}
{% from "jinja_helpers.html" import render_field, render_button, render_checkbox %}
{% block title %}Med-Wiz{% endblock %}
{% block content %}
<div class="container mt-4">
    <h1 class="text-center">Profil Pacjenta, {{ patient.name }}</h1>
    <div class="row">
        <!-- Kolumna z danymi medycznymi -->
        <div class="col-md-4">
            <div class="card my-4">
                <div class="card-header">
                    <h2>Dane</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush" id="comments">
                        <li class="list-group-item" style="font-size: 1.2em;">
                            <p style="font-size: 1.5em;"><b>Tytuł wpisu:</b> {{ meddata.title }}</p>
                            <p><b>Data zamieszczenia:</b> {{ meddata.date }}</p>
                            <p><b>Autor:</b> {{ users.get(meddata.user_id).name }}</p>
                            <p><b>Pacjent:</b> {{ patient.name }}</p>
                            <p><b>Pesel pacjenta:</b> {{ patient.pesel }}</p>    
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Kolumna z diagnozą -->
        <div class="col-md-4">
            <div class="card my-4">
                <div class="card-header">
                    <h2>Diagnoza</h2>
                </div>
                <div class="card-body">
                    <p class="lead" style="font-size: 1.5em;">
                        {{meddata.diagnosis}}
                    </p>
                </div>
            </div>
        </div>

        <!-- Kolumna z plikami do pobrania -->
        <div class="col-md-4">
            <div class="card my-4">
                <div class="card-header">
                    <h2>Pliki</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% if meddata.filename %}
                        <li class="list-group-item text-center">
                            <a href="{{ url_for('static', filename='images/' + meddata.filename) }}" download>
                                <img src="{{ url_for('static', filename='images/' + meddata.filename) }}" alt="Pobierz plik" class="img-thumbnail" style="max-width: 150px;"/>
                                <br />Plik do pobrania
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card my-4">
                <div class="card-header">
                    <h2>Multimedia</h2>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% if meddata.filename.lower().endswith('.mp4') %}
                        <div class="text-center">
                            <video controls autoplay width="500" height="500">
                                <source src="{{ url_for('static', filename='images/'+ meddata.filename) }}" type="video/mp4"/>
                            </video>
                        </div>
                        
                        {% elif meddata.filename %}
                        <div class="text-center">
                            <img src="{{ url_for('static', filename='images/'+ meddata.filename) }}" width="500" height="500" class="img-fluid" alt="Medical Image"/>
                        </div>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

flask-server/website/templates/patient_profile.html
{% extends "base.html" %}{% from "jinja_helpers.html" import render_field %} {%
  from "jinja_helpers.html" import render_button %} {%block title%}Med-Wiz
  Ustawienia{%endblock%}

{% block content %}
<h1 align="center">Profil Pacjenta: {{ patient.name }}</h1>

<div class="container-fluid">
  <div class="row">

    <!-- Center Column: Medical Data and Form -->
    <div class="col-md-5 px-5">
      <h2>Dane Medyczne</h2>
      <br>
      <div class="shadow p-3 mb-5 bg-body rounded">
        <form
          method="post"
          novalidate="true"
          enctype="multipart/form-data"
          action="{{ url_for('views.addPatMed', patientId=patient.id) }}"
        >
          {{ medform.csrf_token }} {{ medform.hidden_tag() }}
          {{ render_field(medform.title) }}
          {{ render_field(medform.text) }}
          {{ medform.file.label }}
          <br />
          {{ medform.file }}
          <br />
          {% if medform.file.errors %}
            {% for error in medform.file.errors %}
            <span style="color:red">{{ error }}</span>
            {% endfor %}
          {% endif %}
          <br /><div align="right">
          {{ render_button(medform.submit) }}
          </div>
        </form>
      </div>
      <div class="shadow p-3 mb-5 bg-body rounded" style="max-height: 300px; overflow-y: scroll;">
        <ul class="list-group list-group-flush" id="medicaldata">
          {% for meddata in medicalRecord %}
          
          <li class="list-group-item border-0" style="font-size:1.2em;">
            <div class="shadow p-2 mb-3 bg-body rounded ">
            <b>Tytuł:</b> {{ meddata.title }}
            <br />
            <b>Opis:</b> {{ meddata.diagnosis[0:50] }}
            <br />
            <b>Data zamieszczenia:</b> {{ meddata.date }} 
            <div align="right">
              <a href="{{ url_for('views.viewMedData', meddataId=meddata.id) }}" class="btn btn-primary mt-3">Zobacz Wpis</a>
              <button type="button" class="btn btn-danger mt-3" onClick="deleteMed('{{meddata.id}}')">Usun</button>
            </div>
          </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>  
    <!-- Right Column: Chat and Form -->
    <div class="col-md-5">
      <h2>Czat</h2>
      <br>
      <div class="shadow p-3 mb-5 bg-body rounded">
      <form method="POST" action="{{ url_for('views.addPatCom', patientId=patient.id) }}">
        {{ comform.csrf_token }}{{ comform.hidden_tag() }}
        {{ render_field(comform.text) }}
        <br />
        <div align="right">
        {{ render_button(comform.submit) }}
      </div>
      </form>
    </div>
      <div class="shadow p-3 mb-5 bg-body rounded" style="max-height: 440px; overflow-y: scroll;">
      <ul class="list-group list-group-flush " id="comments">
        {% for comment in comments %}
        <li class="list-group-item border-0" >
          <div class="shadow p-2 mb-3 bg-body rounded ">
          <strong>{{users.get(comment.user_id).name.capitalize()}}:</strong> {{ comment.text }}
          <button type="button" class="close" onClick="deleteCom('{{ comment.id }}')">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    </div>
  </div>
</div>
{% endblock %}

flask-server/website/templates/patients.html
{% extends "base.html" %}{% from "jinja_helpers.html" import render_field %} {% from "jinja_helpers.html" import render_button %} 
{% block title %}Med-Wiz Rejestracja{% endblock %} 
{% block content %}
<br />
<div class="shadow p-3 mb-5 bg-body rounded">
  <form method="post" novalidate="true">
    {{ form.csrf_token }}{{ form.hidden_tag() }}{{ render_field(form.name) }}
    <br />
    {{ render_field(form.pesel) }}
    <br />
    {{ render_button(form.submit) }}
  </form>
</div>
<br />
<form method="post" novalidate="true">
  {{ search.csrf_token }}{{ search.hidden_tag() }}
  {{ render_field(search.searchResult) }}
  {{ render_button(search.submit) }}
</form>

<div class="container">
  <div class="row">
    <!-- Moi pacjenci column -->
    <div class="col-md-6">
      <h1>Moi pacjenci</h1>
      <div class="shadow p-3 mb-5 bg-body rounded" style="max-height: 260px; overflow-y: scroll;">
      <table class="table table-hover table-bordered table-striped">
        {% for patient in user.patient %}
        <tr>
          <td>
            {{ patient.id }}. <a href="patients/{{ patient.id }}">{{ patient.name }}</a> - Pesel: {{ patient.pesel }}
            <br />
            <a class="btn btn-primary mt-3" href="{{ url_for('views.patientView', patientId=patient.id) }}">Profil</a>
            <button type="button" class="btn btn-danger mt-3" onClick="deleteFromMyPatients('{{ patient.id }}')">Usun z moich pacjentów</button>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    </div>

    <!-- Wszyscy Pacjenci column -->
    <div class="col-md-6">
      <h1>Wszyscy pacjenci</h1>
      <div class="shadow p-3 mb-5 bg-body rounded" style="max-height: 260px; overflow-y: scroll;">
      <table class="table table-hover table-bordered table-striped">
        {% for patient in patients %}
        {% if not patient in user.patient %}
        <tr>
          <td>
            {{ patient.id }}. <a href="patients/{{ patient.id }}">{{ patient.name }}</a> - Pesel: {{ patient.pesel }}
            <br />
            <button type="button" class="btn btn-success mt-3" onClick="addToMyPatients('{{ patient.id }}')">Dodaj do moich</button>
            <button type="button" class="btn btn-danger mt-3" onClick="deletePatient('{{ patient.id }}')">Usun pacjenta</button>
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </table>
    </div>
    </div>
  </div>
</div>
{% endblock %}

flask-server/website/templates/settings.html
{% extends "base.html" %}
{% from "jinja_helpers.html" import render_field %}
{% from "jinja_helpers.html" import render_button %}

{% block title %}Med-Wiz Rejestracja{% endblock %}

{% block content %}
<br />

<div class="container-fluid">
  <div class="row">
    <div class="col-md-5">
      <div class="container">
        <div class="container">
          <form method="post" novalidate="true">
            {{ form.csrf_token }} 
            {{ form.hidden_tag() }}
            
            <h1>Zmiana Hasła</h1>
            {{ render_field(form.password) }}
            {{ render_field(form.repassword) }}
            <br />
            {{ render_button(form.submit) }}
          </form>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <div class="container">
        <div class="container">
          <form method="post" method="post"
          novalidate="true"
          enctype="multipart/form-data">
            {{ user_form.csrf_token }}
            {{ user_form.hidden_tag() }}

            <h1>Profil Użytkownika</h1>
            {{ render_field(user_form.name) }}
            {{ render_field(user_form.surname) }}
            {{ render_field(user_form.specialization) }}
            {{ render_field(user_form.about) }}
            {{ render_field(user_form.phonenumber) }}
            {{ render_field(user_form.picture) }}
            <br />
            {{ render_button(user_form.submit) }}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flask-server/website/templates/sign-up.html
{% extends "base.html" %}{% from "jinja_helpers.html" import render_field %} {%
  from "jinja_helpers.html" import render_button %} {%block title%}Med-Wiz
  Rejestracja{%endblock%} {%block content%}
  <br />
  <div class="shadow p-3 mb-5 bg-body rounded">
  <form method="post" novalidate="true">
    {{ form.csrf_token }} {{form.hidden_tag()}}{{render_field(form.name)}}
    <br />
    {{render_field(form.email)}}
    <br />
    {{render_field(form.password)}}
    <br />
    {{render_field(form.repassword)}}
    <br />
    {{render_button(form.submit)}}
  </form>
  </div>
  <br />
  <table class="table table-hover table-bordered table-striped">
  {% for user in users %} 
  <tr>
  <td>
  {{user.id}}. {{user.name}} - {{user.email}} 
  </td>
  </tr>
  {% endfor %}
  </table>
  {%endblock%}